
##start programs
#compton &
#start-pulseaudio-x11 &
#LightRead &
#
##set displays to vertical
#xrandr --output eDP-1 --off
#
#
#/home/lchilds/Sync/backgrounds/.wallpaper_random.sh &
#/home/lchilds/src/go/src/github.com/lex148/PowerMate/power_mate &
#
##echo -e 'power on\nquit' | bluetoothctl
##echo -e 'connect 00:18:16:4B:39:D5\nquit' | bluetoothctl
#echo 'power on' | bluetoothctl
#echo 'connect 00:18:16:4B:39:D5' | bluetoothctl


#strart wm
exec i3
#exec awesome
